// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Blog() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"section blog-section\" aria-labelledby=\"blog-title\"><div class=\"wrap\"><div class=\"section-head\"><span class=\"eyebrow\">Erik Jermaniš</span><div><h1 id=\"blog-title\">Blog</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p></div></div><div class=\"blog-grid\"><article class=\"blog-card\"><time class=\"mono\" datetime=\"2026-09-01\">01/09/2026</time> <img src=\"/assets/blog-process.svg\" width=\"800\" height=\"400\" alt=\"\" loading=\"lazy\"><h2>Naslov objave 01</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo eget felis tincidunt suscipit.</p></article><article class=\"blog-card\"><time class=\"mono\" datetime=\"2026-09-15\">15/09/2026</time> <img src=\"/assets/blog-decision.svg\" width=\"800\" height=\"400\" alt=\"\" loading=\"lazy\"><h2>Naslov objave 02</h2><p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec ullamcorper nulla non metus auctor fringilla.</p></article></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout(metadata{
			Title:       "Blog | Erik Software",
			Description: "Pišem o razvoju softvera i automatizaciji poslovanja. Dajem korisne savjete i podučavam poduzetnike kako koristiti AI alate.",
			Canonical:   "https://eriksoftware.hr/blog",
			NoIndex:     true,
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
